framework:
    messenger:
        transports:
            rabbitmq:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              options:
                connect_timeout: 30
        routing:
          'App\Domain\Model\Post\PostWasCreated': rabbitmq
          'App\Domain\Model\Post\PostWasDeleted': rabbitmq
          'App\Domain\Model\Forum\ForumWasCreated': rabbitmq
          'App\Domain\Model\Forum\ForumStatusWasChanged': rabbitmq
          'App\Domain\Model\Forum\ForumTitleWasChanged': rabbitmq
